/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.organizador.main;

import br.organizador.modelo.Configuracao;
import br.organizador.modelo.ConfiguracaoPasta;
import java.io.File;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author paulo.gomes
 */
public class Principal extends javax.swing.JFrame {

    private boolean editando = false;
    private Organizador organizador;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        inicializarTable();
        lblId.setVisible(false);
        lblId.setText("0");
        carregarConfiguracoes();
//        organizador = new Organizador();
//        organizador.getConfig().setPastaOrigem("C:\\tmp");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAdicionar = new javax.swing.JButton();
        txtDestino = new javax.swing.JTextField();
        btnBuscarPastaDestino = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNomeEmpresa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtOrigem = new javax.swing.JTextField();
        btnBuscarPastaOrigem = new javax.swing.JButton();
        txtCNPJ = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabConfiguracoes = new javax.swing.JTable();
        btnEditarTabela = new javax.swing.JButton();
        btnExcluirTabela = new javax.swing.JButton();
        btnExecutar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Organizador NFe - edu");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Configuração"));

        jLabel1.setText("CNPJ:");

        jLabel2.setText("Pasta de Destino:");

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/organizador/img/Ok-icon.png"))); // NOI18N
        btnAdicionar.setText("Adicionar");
        btnAdicionar.setToolTipText("Adicionar nova configução de pasta de destino");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        txtDestino.setEnabled(false);

        btnBuscarPastaDestino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/organizador/img/folder-documents-icon.png"))); // NOI18N
        btnBuscarPastaDestino.setToolTipText("Clique para selecionar a pasta de destino");
        btnBuscarPastaDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPastaDestinoActionPerformed(evt);
            }
        });

        lblId.setEnabled(false);

        jLabel3.setText("Nome da Empresa:");

        txtNomeEmpresa.setToolTipText("");

        jLabel4.setText("Pasta de Origem:");

        txtOrigem.setEnabled(false);

        btnBuscarPastaOrigem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/organizador/img/folder-documents-icon.png"))); // NOI18N
        btnBuscarPastaOrigem.setToolTipText("Clique para selecionar a pasta de destino");
        btnBuscarPastaOrigem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPastaOrigemActionPerformed(evt);
            }
        });

        try {
            txtCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtOrigem)
                                .addGap(10, 10, 10)))
                        .addComponent(btnBuscarPastaOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblId)
                            .addComponent(txtNomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnAdicionar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtDestino))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarPastaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBuscarPastaOrigem)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBuscarPastaDestino)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAdicionar)
                        .addComponent(lblId))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jPanel1.setBounds(10, 10, 620, 210);
        jDesktopPane1.add(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Configurações"));

        tabConfiguracoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Empresa", "CNPJ", "Destino"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabConfiguracoes);

        btnEditarTabela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/organizador/img/edit-icon.png"))); // NOI18N
        btnEditarTabela.setText("Editar");
        btnEditarTabela.setToolTipText("Edita o registro selecionado na tabela");
        btnEditarTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarTabelaActionPerformed(evt);
            }
        });

        btnExcluirTabela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/organizador/img/Close-icon.png"))); // NOI18N
        btnExcluirTabela.setText("Excluir");
        btnExcluirTabela.setToolTipText("Exclui o registro selecionado na tabela");
        btnExcluirTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirTabelaActionPerformed(evt);
            }
        });

        btnExecutar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/organizador/img/Play-Normal-icon.png"))); // NOI18N
        btnExecutar.setText("Executar");
        btnExecutar.setToolTipText("Inicia a execução da rotina.");
        btnExecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecutarActionPerformed(evt);
            }
        });

        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/organizador/img/Log-Out-icon.png"))); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnExecutar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditarTabela)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluirTabela)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFechar)
                        .addGap(1, 1, 1)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarTabela)
                    .addComponent(btnExecutar)
                    .addComponent(btnFechar)
                    .addComponent(btnExcluirTabela))
                .addGap(19, 19, 19))
        );

        jPanel2.setBounds(10, 230, 620, 310);
        jDesktopPane1.add(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarPastaDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPastaDestinoActionPerformed
        selecionarPasta(txtDestino, txtDestino.getText());
    }//GEN-LAST:event_btnBuscarPastaDestinoActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        adicionarConfiguracaoPasta();
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnEditarTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarTabelaActionPerformed
        editarConfiguracaoPasta();
    }//GEN-LAST:event_btnEditarTabelaActionPerformed

    private void btnExcluirTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirTabelaActionPerformed
        excluiConfiguracaoPasta();
    }//GEN-LAST:event_btnExcluirTabelaActionPerformed

    private void btnExecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecutarActionPerformed
        organizador.executar();
        JOptionPane.showMessageDialog(this, "Processo Concluido!", "Concluido", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnExecutarActionPerformed

    private void btnBuscarPastaOrigemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPastaOrigemActionPerformed
        selecionarPasta(txtOrigem, txtOrigem.getText());
        salvarPastaOrigem();
    }//GEN-LAST:event_btnBuscarPastaOrigemActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void mostrarErro(Exception ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro do sistema", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnBuscarPastaDestino;
    private javax.swing.JButton btnBuscarPastaOrigem;
    private javax.swing.JButton btnEditarTabela;
    private javax.swing.JButton btnExcluirTabela;
    private javax.swing.JButton btnExecutar;
    private javax.swing.JButton btnFechar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblId;
    private javax.swing.JTable tabConfiguracoes;
    private javax.swing.JFormattedTextField txtCNPJ;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtNomeEmpresa;
    private javax.swing.JTextField txtOrigem;
    // End of variables declaration//GEN-END:variables

    private void adicionarNaTabela(String id, String nomeEmpresa, String cnpj, String pasta) {
        ((DefaultTableModel) tabConfiguracoes.getModel()).addRow(new String[]{id, nomeEmpresa, cnpj, pasta});
    }

    private void editar(boolean editar) {
        this.editando = editar;
        btnEditarTabela.setEnabled(!this.editando);
        btnExcluirTabela.setEnabled(!this.editando);
        if (editar) {
            btnAdicionar.setText("Salvar");
        } else {
            btnAdicionar.setText("Adicionar");
        }
    }

    private void removerLinha(int linha) {
        ((DefaultTableModel) tabConfiguracoes.getModel()).removeRow(linha);
    }

    private void selecionarPasta(JTextField txt, String caminhoInicial) {
        JFileChooser chooser = null;
        if (caminhoInicial != null || caminhoInicial.isEmpty()) {
            chooser = new JFileChooser(caminhoInicial);
        } else {
            chooser = new JFileChooser();
        }
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int res = chooser.showOpenDialog(null);
        if (res == JFileChooser.APPROVE_OPTION) {
            String pasta = chooser.getSelectedFile().getAbsolutePath();
            txt.setText(pasta);
        }
    }

    private void inicializarTable() {
        DefaultTableModel tableModel = new DefaultTableModel(
                new Object[][][][]{},
                new String[]{"ID", "Nome Empresa", "CNPJ", "Pasta de Destino"}) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tabConfiguracoes.setModel(tableModel);

        tabConfiguracoes.getColumnModel().getColumn(0).setMinWidth(0);
        tabConfiguracoes.getColumnModel().getColumn(0).setMaxWidth(0);
        tabConfiguracoes.getColumnModel().getColumn(2).setMinWidth(150);
        tabConfiguracoes.getColumnModel().getColumn(2).setMaxWidth(150);

        tabConfiguracoes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    private void preencherTexto(String id, String nomeEmpresa, String cnpj, String pasta) {
        lblId.setText(id);
        txtNomeEmpresa.setText(nomeEmpresa);
        txtCNPJ.setText(cnpj);
//        txtDestino.setText(pasta);
    }

    private void carregarConfiguracoes() {
        try {
            organizador = new Organizador();
            organizador.carregarConfiguracoes();
            txtOrigem.setText(organizador.getConfig().getPastaOrigem() + "");
            HashMap<String, ConfiguracaoPasta> map = organizador.getConfig().getConfiguracoes();
            String pasta = "";
            for (ConfiguracaoPasta conf : map.values()) {
                this.adicionarNaTabela(conf.getId() + "", conf.getNomeEmpresa(), formatarCNPJ(conf.getCnpj()), conf.getPasta());
                pasta = conf.getPasta();
            }
            if (pasta.contains(File.separator)) {
                txtDestino.setText(pasta.substring(0, pasta.lastIndexOf(File.separator)));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            mostrarErro(ex);
        }

    }

    private void salvarPastaOrigem() {
        if (txtOrigem.getText().trim().isEmpty()) {
            return;
        }
        try {
//            organizador.getConfig().setPastaOrigem(txtPastaRaiz.getText());
            Configuracao config = organizador.getDb().selecionar();
            if (config == null) {
                config = new Configuracao();
            }
            config.setPastaOrigem(txtOrigem.getText());
            organizador.getDb().salvar(config);
            organizador.setConfig(organizador.getDb().selecionar());
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            mostrarErro(ex);
        }
    }

    private String formatarCNPJ(String cnpj) {
        String retorno = cnpj;
        if (cnpj.contains(".")) {
            retorno = cnpj.replaceAll("[^\\d]", "");
        } else {
            retorno = cnpj.substring(0, 2)
                    .concat(".")
                    .concat(cnpj.substring(2, 5))
                    .concat(".")
                    .concat(cnpj.substring(5, 8)
                    .concat("/"))
                    .concat(cnpj.substring(8, 12))
                    .concat("-")
                    .concat(cnpj.substring(12, 14));
        }
        return retorno;
    }

    private void adicionarConfiguracaoPasta() {
        try {
            int id = Integer.parseInt(lblId.getText());
            String nomeEmpresa = txtNomeEmpresa.getText().trim();
            String cnpj = txtCNPJ.getText().trim();
            String pasta = txtDestino.getText().trim();
            if (organizador.getConfig() == null || (organizador.getConfig().getPastaOrigem() == null || organizador.getConfig().getPastaOrigem().isEmpty())) {
                JOptionPane.showMessageDialog(this, "É necessário configurar a pasta de origem dos documentos!", "Alerta", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (pasta.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Selecione a pasta de destino!", "Alerta", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (cnpj.isEmpty() || nomeEmpresa.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Os campos cnpj e nome da empresa são obrigatórios!", "Alerta", JOptionPane.WARNING_MESSAGE);
                return;
            }
            pasta = pasta.concat(File.separator.concat(nomeEmpresa));
            ConfiguracaoPasta configPasta = new ConfiguracaoPasta(id, nomeEmpresa, formatarCNPJ(cnpj), pasta, organizador.getConfig());
            organizador.adicionarConfig(configPasta);
            this.adicionarNaTabela(configPasta.getId() + "", nomeEmpresa, cnpj, pasta);
            preencherTexto("0", "", "", "");
            editar(false);
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            mostrarErro(ex);
        }
    }

    private void editarConfiguracaoPasta() {
        int linha = tabConfiguracoes.getSelectedRow();
        String id = tabConfiguracoes.getModel().getValueAt(linha, 0).toString();
        String nomeEmpresa = (tabConfiguracoes.getModel().getValueAt(linha, 1) != null) ? tabConfiguracoes.getModel().getValueAt(linha, 1).toString() : "";
        String cnpj = tabConfiguracoes.getModel().getValueAt(linha, 2).toString();
        String destino = tabConfiguracoes.getModel().getValueAt(linha, 3).toString();
        removerLinha(linha);
        preencherTexto(id, nomeEmpresa, cnpj, destino);
        editar(true);
    }

    private void excluiConfiguracaoPasta() {
        int linha = tabConfiguracoes.getSelectedRow();
        if (linha != -1) {
            int resposta = JOptionPane.showConfirmDialog(this, "Confima a exclusão do registro ?", "Confirmar Exclusão", JOptionPane.WARNING_MESSAGE);
            if (resposta == JOptionPane.YES_OPTION) {
                try {
                    String id = tabConfiguracoes.getModel().getValueAt(linha, 2).toString();
                    organizador.getDb().excluir(new ConfiguracaoPasta(Integer.parseInt(id)));
                    removerLinha(linha);
                } catch (SQLException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                    mostrarErro(ex);
                }
            }
        }
    }
}
