/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.organizador.main;

import br.organizador.modelo.ConfiguracaoPasta;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author paulo.gomes
 */
public class Principal extends javax.swing.JFrame {

    private boolean editando = false;
    private Organizador organizador;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        inicializarTable();
        lblId.setVisible(false);
        lblId.setText("0");
        carregarConfiguracoes();
//        organizador = new Organizador();
//        organizador.getConfig().setPastaOrigem("C:\\tmp");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCNPJ = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnAdicionar = new javax.swing.JButton();
        txtDestino = new javax.swing.JTextField();
        btnBuscarPasta = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNomeEmpresa = new javax.swing.JTextField();
        btnConfiguracao = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabConfiguracoes = new javax.swing.JTable();
        btnEditarTabela = new javax.swing.JButton();
        btnExcluirTabela = new javax.swing.JButton();
        btnExecutar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Organizador NFe - edu");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Configuração Pasta de Destino"));

        jLabel1.setText("CNPJ:");

        txtCNPJ.setToolTipText("");

        jLabel2.setText("Pasta de Destino:");

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/organizador/img/Ok-icon.png"))); // NOI18N
        btnAdicionar.setText("Adicionar");
        btnAdicionar.setToolTipText("Adicionar nova configução de pasta de destino");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        txtDestino.setEnabled(false);

        btnBuscarPasta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/organizador/img/folder-documents-icon.png"))); // NOI18N
        btnBuscarPasta.setToolTipText("Clique para selecionar a pasta de destino");
        btnBuscarPasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPastaActionPerformed(evt);
            }
        });

        lblId.setEnabled(false);

        jLabel3.setText("Nome da Empresa:");

        txtNomeEmpresa.setToolTipText("");

        btnConfiguracao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/organizador/img/Settings-icon.png"))); // NOI18N
        btnConfiguracao.setText("Configurar Pasta de Origem");
        btnConfiguracao.setToolTipText("Abre uma nova janela para configuração da pasta de origem");
        btnConfiguracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfiguracaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConfiguracao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdicionar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtNomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtDestino))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarPasta, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBuscarPasta)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionar)
                    .addComponent(lblId)
                    .addComponent(btnConfiguracao))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel1.setBounds(10, 10, 620, 200);
        jDesktopPane1.add(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Configurações"));

        tabConfiguracoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Empresa", "CNPJ", "Destino"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabConfiguracoes);

        btnEditarTabela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/organizador/img/edit-icon.png"))); // NOI18N
        btnEditarTabela.setText("Editar");
        btnEditarTabela.setToolTipText("Edita o registro selecionado na tabela");
        btnEditarTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarTabelaActionPerformed(evt);
            }
        });

        btnExcluirTabela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/organizador/img/Close-icon.png"))); // NOI18N
        btnExcluirTabela.setText("Excluir");
        btnExcluirTabela.setToolTipText("Exclui o registro selecionado na tabela");
        btnExcluirTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirTabelaActionPerformed(evt);
            }
        });

        btnExecutar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/organizador/img/Play-Normal-icon.png"))); // NOI18N
        btnExecutar.setText("Executar");
        btnExecutar.setToolTipText("Inicia a execução da rotina.");
        btnExecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecutarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnExecutar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditarTabela)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluirTabela)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarTabela)
                    .addComponent(btnExcluirTabela)
                    .addComponent(btnExecutar))
                .addGap(19, 19, 19))
        );

        jPanel2.setBounds(10, 230, 620, 310);
        jDesktopPane1.add(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarPastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPastaActionPerformed
        selecionarPasta(txtDestino.getText());
    }//GEN-LAST:event_btnBuscarPastaActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        try {
            int id = Integer.parseInt(lblId.getText());
            String nomeEmpresa = txtNomeEmpresa.getText();
            String cnpj = txtCNPJ.getText();
            String pasta = txtDestino.getText();
            if (organizador.getConfig() == null || (organizador.getConfig().getPastaOrigem() == null || organizador.getConfig().getPastaOrigem().isEmpty())) {
                JOptionPane.showMessageDialog(this, "É necessário configurar a pasta de origem dos documentos!", "Alerta", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (cnpj.isEmpty() || pasta.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Os campos cnpj e pasta são obrigatórios!", "Alerta", JOptionPane.WARNING_MESSAGE);
                return;
            }
            this.adicionarNaTabela(id + "", nomeEmpresa, cnpj, pasta);
            organizador.adicionarConfig(new ConfiguracaoPasta(id, nomeEmpresa, cnpj, pasta, organizador.getConfig()));
            preencherTexto("0", "", "", "");
            editar(false);
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnEditarTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarTabelaActionPerformed
        int linha = tabConfiguracoes.getSelectedRow();
        String id = tabConfiguracoes.getModel().getValueAt(linha, 0).toString();
        String nomeEmpresa = (tabConfiguracoes.getModel().getValueAt(linha, 1) != null) ?tabConfiguracoes.getModel().getValueAt(linha, 1).toString(): "";
        String cnpj = tabConfiguracoes.getModel().getValueAt(linha, 2).toString();
        String destino = tabConfiguracoes.getModel().getValueAt(linha, 3).toString();
        removerLinha(linha);
        preencherTexto(id, nomeEmpresa, cnpj, destino);
        editar(true);
    }//GEN-LAST:event_btnEditarTabelaActionPerformed

    private void btnExcluirTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirTabelaActionPerformed
        int linha = tabConfiguracoes.getSelectedRow();
        if (linha != -1) {
            int resposta = JOptionPane.showConfirmDialog(this, "Confima a exclusão do registro ?", "Confirmar Exclusão", JOptionPane.WARNING_MESSAGE);
            if (resposta == JOptionPane.YES_OPTION) {
                try {
                    String id = tabConfiguracoes.getModel().getValueAt(linha, 2).toString();
                    organizador.getDb().excluir(new ConfiguracaoPasta(Integer.parseInt(id)));
                    removerLinha(linha);
                } catch (SQLException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btnExcluirTabelaActionPerformed

    private void btnExecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecutarActionPerformed
        organizador.executar();
        JOptionPane.showMessageDialog(this, "Processo Concluido!", "Concluido", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnExecutarActionPerformed

    private void btnConfiguracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfiguracaoActionPerformed
        ConfiguracaoForm form = new ConfiguracaoForm(this.jDesktopPane1, organizador);
        form.setVisible(true);
    }//GEN-LAST:event_btnConfiguracaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnBuscarPasta;
    private javax.swing.JButton btnConfiguracao;
    private javax.swing.JButton btnEditarTabela;
    private javax.swing.JButton btnExcluirTabela;
    private javax.swing.JButton btnExecutar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblId;
    private javax.swing.JTable tabConfiguracoes;
    private javax.swing.JTextField txtCNPJ;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtNomeEmpresa;
    // End of variables declaration//GEN-END:variables

    private void adicionarNaTabela(String id, String nomeEmpresa, String cnpj, String pasta) {
        ((DefaultTableModel) tabConfiguracoes.getModel()).addRow(new String[]{id, nomeEmpresa, cnpj, pasta});
    }

    private void editar(boolean editar) {
        this.editando = editar;
        btnEditarTabela.setEnabled(!this.editando);
        btnExcluirTabela.setEnabled(!this.editando);
    }

    private void removerLinha(int linha) {
        ((DefaultTableModel) tabConfiguracoes.getModel()).removeRow(linha);
    }

    private void selecionarPasta(String caminhoInicial) {
        JFileChooser chooser = null;
        if (caminhoInicial != null || caminhoInicial.isEmpty()) {
            chooser = new JFileChooser(caminhoInicial);
        } else {
            chooser = new JFileChooser();
        }
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int res = chooser.showOpenDialog(null);
        if (res == JFileChooser.APPROVE_OPTION) {
            String pasta = chooser.getSelectedFile().getAbsolutePath();
            txtDestino.setText(pasta);
        }
    }

    private void inicializarTable() {
        DefaultTableModel tableModel = new DefaultTableModel(
                new Object[][][][]{},
                new String[]{"ID", "Nome Empresa", "CNPJ", "Pasta de Destino"}) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tabConfiguracoes.setModel(tableModel);

        tabConfiguracoes.getColumnModel().getColumn(0).setMinWidth(0);
        tabConfiguracoes.getColumnModel().getColumn(0).setMaxWidth(0);
        tabConfiguracoes.getColumnModel().getColumn(2).setMinWidth(150);
        tabConfiguracoes.getColumnModel().getColumn(2).setMaxWidth(150);

        tabConfiguracoes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    private void preencherTexto(String id, String nomeEmpresa, String cnpj, String pasta) {
        lblId.setText(id);
        txtNomeEmpresa.setText(nomeEmpresa);
        txtCNPJ.setText(cnpj);
        txtDestino.setText(pasta);
    }

    private void carregarConfiguracoes() {
        try {
            organizador = new Organizador();
            organizador.carregarConfiguracoes();
            HashMap<String, ConfiguracaoPasta> map = organizador.getConfig().getConfiguracoes();
            for (ConfiguracaoPasta conf : map.values()) {
                this.adicionarNaTabela(conf.getId() + "", conf.getNomeEmpresa(), conf.getCnpj(), conf.getPasta());
            }
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
}
